name: Build all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build frontend app
      uses: actions/setup-node@v1      
        with:
          node-version: 14      
      run: npm ci
        working-directory: ./frontend
      run: npm run build
        working-directory: ./frontend


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
