name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build frontend               
        run: |
          npm ci
          npm run build
        working-directory: ./frontend        
       
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="lolover-$tag"        
          go build -v ./... -o "$release_name"        
          tar czvf "${release_name}.tar.gz" "$release_name"

          rm "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "lolover*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}